[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
optimizer=true
optimizer_runs=200
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]
# remappings = [
#     "@openzeppelin/contracts=node_modules/@openzeppelin/contracts/"
# ]

[rpc_endpoints]
arb="https://"
op="https://"

